language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t gadagi/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true gadagi/docker-react npm run test -- --coverage